name: dt-model-wine-quality
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: model_runner
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |

          # Your ML workflow goes here
          pip install -r requirements.txt
          python pipes/decision_tree_train.py

          echo "## DT Model metrics" > report.md
          cat decision_metrics.txt >> report.md

          echo "## DT Model viz" >> report.md
          cml-publish dtfeature_importance.png --md >> report.md
          cml-publish dtresiduals.png --md >> report.md

          cml-send-comment report.md
