name: knn-model-wine-quality
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: model_runner
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |

          # Your ML workflow goes here
          pip install -r requirements.txt
          python pipes/knn_train.py

          echo "## KNN Model metrics" > report.md
          cat knnmetrics.txt >> report.md

          echo "## KNN Model viz" >> report.md
          cml-publish knn_residuals.png --md >> report.md

          cml-send-comment report.md
